

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class common_propertycontactperson_translate : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the common_propertycontactperson_translate entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public common_propertycontactperson_translate()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public common_propertycontactperson_translate(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.common_propertycontactperson_translate> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void common_propertycontactperson_translate_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void common_propertycontactperson_translate_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ContactPersonTranslateID
        {
            get
            {
                return global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties.ContactPersonTranslateID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactPersonTranslateID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactPersonTranslateID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactPersonTranslateID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ContactPersonName
        {
            get
            {
                return global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties.ContactPersonName);
            }
            set
            {
                global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties.ContactPersonName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactPersonName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactPersonName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactPersonName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string FullName
        {
            get
            {
                return global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties.FullName);
            }
            set
            {
                global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties.FullName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FullName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FullName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FullName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Address
        {
            get
            {
                return global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties.Address);
            }
            set
            {
                global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties.Address, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Address_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Address_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Address_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> CreatedDate
        {
            get
            {
                return global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties.CreatedDate);
            }
            set
            {
                global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties.CreatedDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties.ModifiedDate);
            }
            set
            {
                global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties.ModifiedDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<bool> IsTranslationReviewed
        {
            get
            {
                return global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties.IsTranslationReviewed);
            }
            set
            {
                global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties.IsTranslationReviewed, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsTranslationReviewed_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsTranslationReviewed_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsTranslationReviewed_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.vilani_language vilani_language1
        {
            get
            {
                return global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties.vilani_language1);
            }
            set
            {
                global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties.vilani_language1, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void vilani_language1_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void vilani_language1_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void vilani_language1_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.common_propertycontactperson common_propertycontactperson
        {
            get
            {
                return global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties.common_propertycontactperson);
            }
            set
            {
                global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties.common_propertycontactperson, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void common_propertycontactperson_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void common_propertycontactperson_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void common_propertycontactperson_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.common_propertycontactperson_translate,
                global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass,
                global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.IImplementation,
                global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties.ContactPersonTranslateID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass>.Entry
                __common_propertycontactperson_translateEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass>.Entry(
                    global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.__common_propertycontactperson_translate_CreateNew,
                    global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.__common_propertycontactperson_translate_Created,
                    global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.__common_propertycontactperson_translate_AllowSaveWithErrors);
            private static global::LightSwitchApplication.common_propertycontactperson_translate __common_propertycontactperson_translate_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.common_propertycontactperson_translate> es)
            {
                return new global::LightSwitchApplication.common_propertycontactperson_translate(es);
            }
            private static void __common_propertycontactperson_translate_Created(global::LightSwitchApplication.common_propertycontactperson_translate e)
            {
                e.common_propertycontactperson_translate_Created();
            }
            private static bool __common_propertycontactperson_translate_AllowSaveWithErrors(global::LightSwitchApplication.common_propertycontactperson_translate e)
            {
                bool result = false;
                e.common_propertycontactperson_translate_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, int> ContactPersonTranslateID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties.ContactPersonTranslateID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, string> ContactPersonName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties.ContactPersonName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, string> FullName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties.FullName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, string> Address
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties.Address) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::System.Nullable<global::System.DateTime>> CreatedDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties.CreatedDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::System.Nullable<global::System.DateTime>> ModifiedDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties.ModifiedDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::System.Nullable<bool>> IsTranslationReviewed
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties.IsTranslationReviewed) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::System.Nullable<bool>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::LightSwitchApplication.vilani_language> vilani_language1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties.vilani_language1) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::LightSwitchApplication.vilani_language>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::LightSwitchApplication.common_propertycontactperson> common_propertycontactperson
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties.common_propertycontactperson) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::LightSwitchApplication.common_propertycontactperson>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int ContactPersonTranslateID { get; }
                new string ContactPersonName { get; set; }
                new string FullName { get; set; }
                new string Address { get; set; }
                new global::System.Nullable<global::System.DateTime> CreatedDate { get; set; }
                new global::System.Nullable<global::System.DateTime> ModifiedDate { get; set; }
                new global::System.Nullable<bool> IsTranslationReviewed { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation vilani_language1 { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation common_propertycontactperson { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, int>.Entry
                    ContactPersonTranslateID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, int>.Entry(
                        "ContactPersonTranslateID",
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._ContactPersonTranslateID_Stub,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._ContactPersonTranslateID_ComputeIsReadOnly,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._ContactPersonTranslateID_Validate,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._ContactPersonTranslateID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._ContactPersonTranslateID_OnValueChanged);
                private static void _ContactPersonTranslateID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, int>.Data> c, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._ContactPersonTranslateID, sf);
                }
                private static bool _ContactPersonTranslateID_ComputeIsReadOnly(global::LightSwitchApplication.common_propertycontactperson_translate e)
                {
                    bool result = false;
                    e.ContactPersonTranslateID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ContactPersonTranslateID_Validate(global::LightSwitchApplication.common_propertycontactperson_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ContactPersonTranslateID_Validate(r);
                }
                private static int _ContactPersonTranslateID_GetImplementationValue(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.ContactPersonTranslateID;
                }
                private static void _ContactPersonTranslateID_OnValueChanged(global::LightSwitchApplication.common_propertycontactperson_translate e)
                {
                    e.ContactPersonTranslateID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, string>.Entry
                    ContactPersonName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, string>.Entry(
                        "ContactPersonName",
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._ContactPersonName_Stub,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._ContactPersonName_ComputeIsReadOnly,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._ContactPersonName_Validate,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._ContactPersonName_GetImplementationValue,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._ContactPersonName_SetImplementationValue,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._ContactPersonName_OnValueChanged);
                private static void _ContactPersonName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, string>.Data> c, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._ContactPersonName, sf);
                }
                private static bool _ContactPersonName_ComputeIsReadOnly(global::LightSwitchApplication.common_propertycontactperson_translate e)
                {
                    bool result = false;
                    e.ContactPersonName_IsReadOnly(ref result);
                    return result;
                }
                private static void _ContactPersonName_Validate(global::LightSwitchApplication.common_propertycontactperson_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ContactPersonName_Validate(r);
                }
                private static string _ContactPersonName_GetImplementationValue(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.ContactPersonName;
                }
                private static void _ContactPersonName_SetImplementationValue(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ContactPersonName = v;
                }
                private static void _ContactPersonName_OnValueChanged(global::LightSwitchApplication.common_propertycontactperson_translate e)
                {
                    e.ContactPersonName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, string>.Entry
                    FullName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, string>.Entry(
                        "FullName",
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._FullName_Stub,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._FullName_ComputeIsReadOnly,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._FullName_Validate,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._FullName_GetImplementationValue,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._FullName_SetImplementationValue,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._FullName_OnValueChanged);
                private static void _FullName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, string>.Data> c, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._FullName, sf);
                }
                private static bool _FullName_ComputeIsReadOnly(global::LightSwitchApplication.common_propertycontactperson_translate e)
                {
                    bool result = false;
                    e.FullName_IsReadOnly(ref result);
                    return result;
                }
                private static void _FullName_Validate(global::LightSwitchApplication.common_propertycontactperson_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.FullName_Validate(r);
                }
                private static string _FullName_GetImplementationValue(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.FullName;
                }
                private static void _FullName_SetImplementationValue(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass d, string v)
                {
                    d.ImplementationEntity.FullName = v;
                }
                private static void _FullName_OnValueChanged(global::LightSwitchApplication.common_propertycontactperson_translate e)
                {
                    e.FullName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, string>.Entry
                    Address = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, string>.Entry(
                        "Address",
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._Address_Stub,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._Address_ComputeIsReadOnly,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._Address_Validate,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._Address_GetImplementationValue,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._Address_SetImplementationValue,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._Address_OnValueChanged);
                private static void _Address_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, string>.Data> c, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._Address, sf);
                }
                private static bool _Address_ComputeIsReadOnly(global::LightSwitchApplication.common_propertycontactperson_translate e)
                {
                    bool result = false;
                    e.Address_IsReadOnly(ref result);
                    return result;
                }
                private static void _Address_Validate(global::LightSwitchApplication.common_propertycontactperson_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Address_Validate(r);
                }
                private static string _Address_GetImplementationValue(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.Address;
                }
                private static void _Address_SetImplementationValue(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Address = v;
                }
                private static void _Address_OnValueChanged(global::LightSwitchApplication.common_propertycontactperson_translate e)
                {
                    e.Address_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    CreatedDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "CreatedDate",
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._CreatedDate_Stub,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._CreatedDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._CreatedDate_Validate,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._CreatedDate_GetImplementationValue,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._CreatedDate_SetImplementationValue,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._CreatedDate_OnValueChanged);
                private static void _CreatedDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedDate, sf);
                }
                private static bool _CreatedDate_ComputeIsReadOnly(global::LightSwitchApplication.common_propertycontactperson_translate e)
                {
                    bool result = false;
                    e.CreatedDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedDate_Validate(global::LightSwitchApplication.common_propertycontactperson_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _CreatedDate_GetImplementationValue(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedDate;
                }
                private static void _CreatedDate_SetImplementationValue(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.CreatedDate = global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _CreatedDate_OnValueChanged(global::LightSwitchApplication.common_propertycontactperson_translate e)
                {
                    e.CreatedDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    ModifiedDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "ModifiedDate",
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._ModifiedDate_Stub,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._ModifiedDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._ModifiedDate_Validate,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._ModifiedDate_GetImplementationValue,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._ModifiedDate_SetImplementationValue,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._ModifiedDate_OnValueChanged);
                private static void _ModifiedDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedDate, sf);
                }
                private static bool _ModifiedDate_ComputeIsReadOnly(global::LightSwitchApplication.common_propertycontactperson_translate e)
                {
                    bool result = false;
                    e.ModifiedDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedDate_Validate(global::LightSwitchApplication.common_propertycontactperson_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _ModifiedDate_GetImplementationValue(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedDate;
                }
                private static void _ModifiedDate_SetImplementationValue(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.ModifiedDate = global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _ModifiedDate_OnValueChanged(global::LightSwitchApplication.common_propertycontactperson_translate e)
                {
                    e.ModifiedDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::System.Nullable<bool>>.Entry
                    IsTranslationReviewed = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::System.Nullable<bool>>.Entry(
                        "IsTranslationReviewed",
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._IsTranslationReviewed_Stub,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._IsTranslationReviewed_ComputeIsReadOnly,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._IsTranslationReviewed_Validate,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._IsTranslationReviewed_GetImplementationValue,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._IsTranslationReviewed_SetImplementationValue,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._IsTranslationReviewed_OnValueChanged);
                private static void _IsTranslationReviewed_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::System.Nullable<bool>>.Data> c, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._IsTranslationReviewed, sf);
                }
                private static bool _IsTranslationReviewed_ComputeIsReadOnly(global::LightSwitchApplication.common_propertycontactperson_translate e)
                {
                    bool result = false;
                    e.IsTranslationReviewed_IsReadOnly(ref result);
                    return result;
                }
                private static void _IsTranslationReviewed_Validate(global::LightSwitchApplication.common_propertycontactperson_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.IsTranslationReviewed_Validate(r);
                }
                private static global::System.Nullable<bool> _IsTranslationReviewed_GetImplementationValue(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.IsTranslationReviewed;
                }
                private static void _IsTranslationReviewed_SetImplementationValue(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass d, global::System.Nullable<bool> v)
                {
                    d.ImplementationEntity.IsTranslationReviewed = v;
                }
                private static void _IsTranslationReviewed_OnValueChanged(global::LightSwitchApplication.common_propertycontactperson_translate e)
                {
                    e.IsTranslationReviewed_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::LightSwitchApplication.vilani_language>.Entry
                    vilani_language1 = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::LightSwitchApplication.vilani_language>.Entry(
                        "vilani_language1",
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._vilani_language1_Stub,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._vilani_language1_ComputeIsReadOnly,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._vilani_language1_Validate,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._vilani_language1_GetCoreImplementationValue,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._vilani_language1_GetImplementationValue,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._vilani_language1_SetImplementationValue,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._vilani_language1_Refresh,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._vilani_language1_OnValueChanged);
                private static void _vilani_language1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::LightSwitchApplication.vilani_language>.Data> c, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._vilani_language1, sf);
                }
                private static bool _vilani_language1_ComputeIsReadOnly(global::LightSwitchApplication.common_propertycontactperson_translate e)
                {
                    bool result = false;
                    e.vilani_language1_IsReadOnly(ref result);
                    return result;
                }
                private static void _vilani_language1_Validate(global::LightSwitchApplication.common_propertycontactperson_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.vilani_language1_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _vilani_language1_GetCoreImplementationValue(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.vilani_language1;
                }
                private static global::LightSwitchApplication.vilani_language _vilani_language1_GetImplementationValue(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass>(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties.vilani_language1, ref d._vilani_language1);
                }
                private static void _vilani_language1_SetImplementationValue(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass d, global::LightSwitchApplication.vilani_language v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties.vilani_language1, ref d._vilani_language1, (i, ev) => i.vilani_language1 = ev, v);
                }
                private static void _vilani_language1_Refresh(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties.vilani_language1, ref d._vilani_language1);
                }
                private static void _vilani_language1_OnValueChanged(global::LightSwitchApplication.common_propertycontactperson_translate e)
                {
                    e.vilani_language1_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::LightSwitchApplication.common_propertycontactperson>.Entry
                    common_propertycontactperson = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::LightSwitchApplication.common_propertycontactperson>.Entry(
                        "common_propertycontactperson",
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._common_propertycontactperson_Stub,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._common_propertycontactperson_ComputeIsReadOnly,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._common_propertycontactperson_Validate,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._common_propertycontactperson_GetCoreImplementationValue,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._common_propertycontactperson_GetImplementationValue,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._common_propertycontactperson_SetImplementationValue,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._common_propertycontactperson_Refresh,
                        global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties._common_propertycontactperson_OnValueChanged);
                private static void _common_propertycontactperson_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::LightSwitchApplication.common_propertycontactperson>.Data> c, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._common_propertycontactperson, sf);
                }
                private static bool _common_propertycontactperson_ComputeIsReadOnly(global::LightSwitchApplication.common_propertycontactperson_translate e)
                {
                    bool result = false;
                    e.common_propertycontactperson_IsReadOnly(ref result);
                    return result;
                }
                private static void _common_propertycontactperson_Validate(global::LightSwitchApplication.common_propertycontactperson_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.common_propertycontactperson_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _common_propertycontactperson_GetCoreImplementationValue(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.common_propertycontactperson;
                }
                private static global::LightSwitchApplication.common_propertycontactperson _common_propertycontactperson_GetImplementationValue(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.common_propertycontactperson, global::LightSwitchApplication.common_propertycontactperson.DetailsClass>(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties.common_propertycontactperson, ref d._common_propertycontactperson);
                }
                private static void _common_propertycontactperson_SetImplementationValue(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass d, global::LightSwitchApplication.common_propertycontactperson v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties.common_propertycontactperson, ref d._common_propertycontactperson, (i, ev) => i.common_propertycontactperson = ev, v);
                }
                private static void _common_propertycontactperson_Refresh(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass.PropertySetProperties.common_propertycontactperson, ref d._common_propertycontactperson);
                }
                private static void _common_propertycontactperson_OnValueChanged(global::LightSwitchApplication.common_propertycontactperson_translate e)
                {
                    e.common_propertycontactperson_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, int>.Data _ContactPersonTranslateID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, string>.Data _ContactPersonName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, string>.Data _FullName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, string>.Data _Address;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _CreatedDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _ModifiedDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::System.Nullable<bool>>.Data _IsTranslationReviewed;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::LightSwitchApplication.vilani_language>.Data _vilani_language1;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass, global::LightSwitchApplication.common_propertycontactperson>.Data _common_propertycontactperson;
            
        }
    
        #endregion
    }
    
    #endregion
}
