

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class common_developerlist_translate : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the common_developerlist_translate entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public common_developerlist_translate()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public common_developerlist_translate(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.common_developerlist_translate> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.common_developerlist_translate.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void common_developerlist_translate_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void common_developerlist_translate_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int DeveloperTranslateID
        {
            get
            {
                return global::LightSwitchApplication.common_developerlist_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.DeveloperTranslateID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DeveloperTranslateID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DeveloperTranslateID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DeveloperTranslateID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string DeveloperName
        {
            get
            {
                return global::LightSwitchApplication.common_developerlist_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.DeveloperName);
            }
            set
            {
                global::LightSwitchApplication.common_developerlist_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.DeveloperName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DeveloperName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DeveloperName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DeveloperName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CompanyName
        {
            get
            {
                return global::LightSwitchApplication.common_developerlist_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.CompanyName);
            }
            set
            {
                global::LightSwitchApplication.common_developerlist_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.CompanyName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CompanyName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CompanyName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CompanyName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string AboutUs
        {
            get
            {
                return global::LightSwitchApplication.common_developerlist_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.AboutUs);
            }
            set
            {
                global::LightSwitchApplication.common_developerlist_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.AboutUs, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AboutUs_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AboutUs_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AboutUs_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ContactPersonName
        {
            get
            {
                return global::LightSwitchApplication.common_developerlist_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.ContactPersonName);
            }
            set
            {
                global::LightSwitchApplication.common_developerlist_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.ContactPersonName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactPersonName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactPersonName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactPersonName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Description
        {
            get
            {
                return global::LightSwitchApplication.common_developerlist_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.Description);
            }
            set
            {
                global::LightSwitchApplication.common_developerlist_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.Description, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return global::LightSwitchApplication.common_developerlist_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.CreateDate);
            }
            set
            {
                global::LightSwitchApplication.common_developerlist_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.CreateDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return global::LightSwitchApplication.common_developerlist_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.ModifiedDate);
            }
            set
            {
                global::LightSwitchApplication.common_developerlist_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.ModifiedDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<bool> IsTranslationReviewed
        {
            get
            {
                return global::LightSwitchApplication.common_developerlist_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.IsTranslationReviewed);
            }
            set
            {
                global::LightSwitchApplication.common_developerlist_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.IsTranslationReviewed, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsTranslationReviewed_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsTranslationReviewed_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsTranslationReviewed_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> DeletedOn
        {
            get
            {
                return global::LightSwitchApplication.common_developerlist_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.DeletedOn);
            }
            set
            {
                global::LightSwitchApplication.common_developerlist_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.DeletedOn, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DeletedOn_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DeletedOn_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DeletedOn_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.common_developerlist common_developerlist
        {
            get
            {
                return global::LightSwitchApplication.common_developerlist_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.common_developerlist);
            }
            set
            {
                global::LightSwitchApplication.common_developerlist_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.common_developerlist, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void common_developerlist_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void common_developerlist_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void common_developerlist_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.vilani_language vilani_language1
        {
            get
            {
                return global::LightSwitchApplication.common_developerlist_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.vilani_language1);
            }
            set
            {
                global::LightSwitchApplication.common_developerlist_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.vilani_language1, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void vilani_language1_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void vilani_language1_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void vilani_language1_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.common_developerlist_translate,
                global::LightSwitchApplication.common_developerlist_translate.DetailsClass,
                global::LightSwitchApplication.common_developerlist_translate.DetailsClass.IImplementation,
                global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.DeveloperTranslateID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass>.Entry
                __common_developerlist_translateEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass>.Entry(
                    global::LightSwitchApplication.common_developerlist_translate.DetailsClass.__common_developerlist_translate_CreateNew,
                    global::LightSwitchApplication.common_developerlist_translate.DetailsClass.__common_developerlist_translate_Created,
                    global::LightSwitchApplication.common_developerlist_translate.DetailsClass.__common_developerlist_translate_AllowSaveWithErrors);
            private static global::LightSwitchApplication.common_developerlist_translate __common_developerlist_translate_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.common_developerlist_translate> es)
            {
                return new global::LightSwitchApplication.common_developerlist_translate(es);
            }
            private static void __common_developerlist_translate_Created(global::LightSwitchApplication.common_developerlist_translate e)
            {
                e.common_developerlist_translate_Created();
            }
            private static bool __common_developerlist_translate_AllowSaveWithErrors(global::LightSwitchApplication.common_developerlist_translate e)
            {
                bool result = false;
                e.common_developerlist_translate_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, int> DeveloperTranslateID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.DeveloperTranslateID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, string> DeveloperName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.DeveloperName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, string> CompanyName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.CompanyName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, string> AboutUs
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.AboutUs) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, string> ContactPersonName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.ContactPersonName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, string> Description
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.Description) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::System.Nullable<global::System.DateTime>> CreateDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.CreateDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::System.Nullable<global::System.DateTime>> ModifiedDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.ModifiedDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::System.Nullable<bool>> IsTranslationReviewed
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.IsTranslationReviewed) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::System.Nullable<bool>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::System.Nullable<global::System.DateTime>> DeletedOn
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.DeletedOn) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::LightSwitchApplication.common_developerlist> common_developerlist
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.common_developerlist) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::LightSwitchApplication.common_developerlist>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::LightSwitchApplication.vilani_language> vilani_language1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.vilani_language1) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::LightSwitchApplication.vilani_language>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int DeveloperTranslateID { get; }
                new string DeveloperName { get; set; }
                new string CompanyName { get; set; }
                new string AboutUs { get; set; }
                new string ContactPersonName { get; set; }
                new string Description { get; set; }
                new global::System.Nullable<global::System.DateTime> CreateDate { get; set; }
                new global::System.Nullable<global::System.DateTime> ModifiedDate { get; set; }
                new global::System.Nullable<bool> IsTranslationReviewed { get; set; }
                new global::System.Nullable<global::System.DateTime> DeletedOn { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation common_developerlist { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation vilani_language1 { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, int>.Entry
                    DeveloperTranslateID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, int>.Entry(
                        "DeveloperTranslateID",
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._DeveloperTranslateID_Stub,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._DeveloperTranslateID_ComputeIsReadOnly,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._DeveloperTranslateID_Validate,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._DeveloperTranslateID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._DeveloperTranslateID_OnValueChanged);
                private static void _DeveloperTranslateID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, int>.Data> c, global::LightSwitchApplication.common_developerlist_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._DeveloperTranslateID, sf);
                }
                private static bool _DeveloperTranslateID_ComputeIsReadOnly(global::LightSwitchApplication.common_developerlist_translate e)
                {
                    bool result = false;
                    e.DeveloperTranslateID_IsReadOnly(ref result);
                    return result;
                }
                private static void _DeveloperTranslateID_Validate(global::LightSwitchApplication.common_developerlist_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DeveloperTranslateID_Validate(r);
                }
                private static int _DeveloperTranslateID_GetImplementationValue(global::LightSwitchApplication.common_developerlist_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.DeveloperTranslateID;
                }
                private static void _DeveloperTranslateID_OnValueChanged(global::LightSwitchApplication.common_developerlist_translate e)
                {
                    e.DeveloperTranslateID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, string>.Entry
                    DeveloperName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, string>.Entry(
                        "DeveloperName",
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._DeveloperName_Stub,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._DeveloperName_ComputeIsReadOnly,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._DeveloperName_Validate,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._DeveloperName_GetImplementationValue,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._DeveloperName_SetImplementationValue,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._DeveloperName_OnValueChanged);
                private static void _DeveloperName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, string>.Data> c, global::LightSwitchApplication.common_developerlist_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._DeveloperName, sf);
                }
                private static bool _DeveloperName_ComputeIsReadOnly(global::LightSwitchApplication.common_developerlist_translate e)
                {
                    bool result = false;
                    e.DeveloperName_IsReadOnly(ref result);
                    return result;
                }
                private static void _DeveloperName_Validate(global::LightSwitchApplication.common_developerlist_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DeveloperName_Validate(r);
                }
                private static string _DeveloperName_GetImplementationValue(global::LightSwitchApplication.common_developerlist_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.DeveloperName;
                }
                private static void _DeveloperName_SetImplementationValue(global::LightSwitchApplication.common_developerlist_translate.DetailsClass d, string v)
                {
                    d.ImplementationEntity.DeveloperName = v;
                }
                private static void _DeveloperName_OnValueChanged(global::LightSwitchApplication.common_developerlist_translate e)
                {
                    e.DeveloperName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, string>.Entry
                    CompanyName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, string>.Entry(
                        "CompanyName",
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._CompanyName_Stub,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._CompanyName_ComputeIsReadOnly,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._CompanyName_Validate,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._CompanyName_GetImplementationValue,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._CompanyName_SetImplementationValue,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._CompanyName_OnValueChanged);
                private static void _CompanyName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, string>.Data> c, global::LightSwitchApplication.common_developerlist_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._CompanyName, sf);
                }
                private static bool _CompanyName_ComputeIsReadOnly(global::LightSwitchApplication.common_developerlist_translate e)
                {
                    bool result = false;
                    e.CompanyName_IsReadOnly(ref result);
                    return result;
                }
                private static void _CompanyName_Validate(global::LightSwitchApplication.common_developerlist_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CompanyName_Validate(r);
                }
                private static string _CompanyName_GetImplementationValue(global::LightSwitchApplication.common_developerlist_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.CompanyName;
                }
                private static void _CompanyName_SetImplementationValue(global::LightSwitchApplication.common_developerlist_translate.DetailsClass d, string v)
                {
                    d.ImplementationEntity.CompanyName = v;
                }
                private static void _CompanyName_OnValueChanged(global::LightSwitchApplication.common_developerlist_translate e)
                {
                    e.CompanyName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, string>.Entry
                    AboutUs = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, string>.Entry(
                        "AboutUs",
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._AboutUs_Stub,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._AboutUs_ComputeIsReadOnly,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._AboutUs_Validate,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._AboutUs_GetImplementationValue,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._AboutUs_SetImplementationValue,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._AboutUs_OnValueChanged);
                private static void _AboutUs_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, string>.Data> c, global::LightSwitchApplication.common_developerlist_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._AboutUs, sf);
                }
                private static bool _AboutUs_ComputeIsReadOnly(global::LightSwitchApplication.common_developerlist_translate e)
                {
                    bool result = false;
                    e.AboutUs_IsReadOnly(ref result);
                    return result;
                }
                private static void _AboutUs_Validate(global::LightSwitchApplication.common_developerlist_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.AboutUs_Validate(r);
                }
                private static string _AboutUs_GetImplementationValue(global::LightSwitchApplication.common_developerlist_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.AboutUs;
                }
                private static void _AboutUs_SetImplementationValue(global::LightSwitchApplication.common_developerlist_translate.DetailsClass d, string v)
                {
                    d.ImplementationEntity.AboutUs = v;
                }
                private static void _AboutUs_OnValueChanged(global::LightSwitchApplication.common_developerlist_translate e)
                {
                    e.AboutUs_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, string>.Entry
                    ContactPersonName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, string>.Entry(
                        "ContactPersonName",
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._ContactPersonName_Stub,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._ContactPersonName_ComputeIsReadOnly,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._ContactPersonName_Validate,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._ContactPersonName_GetImplementationValue,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._ContactPersonName_SetImplementationValue,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._ContactPersonName_OnValueChanged);
                private static void _ContactPersonName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, string>.Data> c, global::LightSwitchApplication.common_developerlist_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._ContactPersonName, sf);
                }
                private static bool _ContactPersonName_ComputeIsReadOnly(global::LightSwitchApplication.common_developerlist_translate e)
                {
                    bool result = false;
                    e.ContactPersonName_IsReadOnly(ref result);
                    return result;
                }
                private static void _ContactPersonName_Validate(global::LightSwitchApplication.common_developerlist_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ContactPersonName_Validate(r);
                }
                private static string _ContactPersonName_GetImplementationValue(global::LightSwitchApplication.common_developerlist_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.ContactPersonName;
                }
                private static void _ContactPersonName_SetImplementationValue(global::LightSwitchApplication.common_developerlist_translate.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ContactPersonName = v;
                }
                private static void _ContactPersonName_OnValueChanged(global::LightSwitchApplication.common_developerlist_translate e)
                {
                    e.ContactPersonName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, string>.Entry
                    Description = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, string>.Entry(
                        "Description",
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._Description_Stub,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._Description_ComputeIsReadOnly,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._Description_Validate,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._Description_GetImplementationValue,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._Description_SetImplementationValue,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._Description_OnValueChanged);
                private static void _Description_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, string>.Data> c, global::LightSwitchApplication.common_developerlist_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._Description, sf);
                }
                private static bool _Description_ComputeIsReadOnly(global::LightSwitchApplication.common_developerlist_translate e)
                {
                    bool result = false;
                    e.Description_IsReadOnly(ref result);
                    return result;
                }
                private static void _Description_Validate(global::LightSwitchApplication.common_developerlist_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Description_Validate(r);
                }
                private static string _Description_GetImplementationValue(global::LightSwitchApplication.common_developerlist_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.Description;
                }
                private static void _Description_SetImplementationValue(global::LightSwitchApplication.common_developerlist_translate.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Description = v;
                }
                private static void _Description_OnValueChanged(global::LightSwitchApplication.common_developerlist_translate e)
                {
                    e.Description_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    CreateDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "CreateDate",
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._CreateDate_Stub,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._CreateDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._CreateDate_Validate,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._CreateDate_GetImplementationValue,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._CreateDate_SetImplementationValue,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._CreateDate_OnValueChanged);
                private static void _CreateDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.common_developerlist_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._CreateDate, sf);
                }
                private static bool _CreateDate_ComputeIsReadOnly(global::LightSwitchApplication.common_developerlist_translate e)
                {
                    bool result = false;
                    e.CreateDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreateDate_Validate(global::LightSwitchApplication.common_developerlist_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreateDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _CreateDate_GetImplementationValue(global::LightSwitchApplication.common_developerlist_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.CreateDate;
                }
                private static void _CreateDate_SetImplementationValue(global::LightSwitchApplication.common_developerlist_translate.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.CreateDate = global::LightSwitchApplication.common_developerlist_translate.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _CreateDate_OnValueChanged(global::LightSwitchApplication.common_developerlist_translate e)
                {
                    e.CreateDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    ModifiedDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "ModifiedDate",
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._ModifiedDate_Stub,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._ModifiedDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._ModifiedDate_Validate,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._ModifiedDate_GetImplementationValue,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._ModifiedDate_SetImplementationValue,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._ModifiedDate_OnValueChanged);
                private static void _ModifiedDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.common_developerlist_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedDate, sf);
                }
                private static bool _ModifiedDate_ComputeIsReadOnly(global::LightSwitchApplication.common_developerlist_translate e)
                {
                    bool result = false;
                    e.ModifiedDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedDate_Validate(global::LightSwitchApplication.common_developerlist_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _ModifiedDate_GetImplementationValue(global::LightSwitchApplication.common_developerlist_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedDate;
                }
                private static void _ModifiedDate_SetImplementationValue(global::LightSwitchApplication.common_developerlist_translate.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.ModifiedDate = global::LightSwitchApplication.common_developerlist_translate.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _ModifiedDate_OnValueChanged(global::LightSwitchApplication.common_developerlist_translate e)
                {
                    e.ModifiedDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::System.Nullable<bool>>.Entry
                    IsTranslationReviewed = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::System.Nullable<bool>>.Entry(
                        "IsTranslationReviewed",
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._IsTranslationReviewed_Stub,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._IsTranslationReviewed_ComputeIsReadOnly,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._IsTranslationReviewed_Validate,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._IsTranslationReviewed_GetImplementationValue,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._IsTranslationReviewed_SetImplementationValue,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._IsTranslationReviewed_OnValueChanged);
                private static void _IsTranslationReviewed_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::System.Nullable<bool>>.Data> c, global::LightSwitchApplication.common_developerlist_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._IsTranslationReviewed, sf);
                }
                private static bool _IsTranslationReviewed_ComputeIsReadOnly(global::LightSwitchApplication.common_developerlist_translate e)
                {
                    bool result = false;
                    e.IsTranslationReviewed_IsReadOnly(ref result);
                    return result;
                }
                private static void _IsTranslationReviewed_Validate(global::LightSwitchApplication.common_developerlist_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.IsTranslationReviewed_Validate(r);
                }
                private static global::System.Nullable<bool> _IsTranslationReviewed_GetImplementationValue(global::LightSwitchApplication.common_developerlist_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.IsTranslationReviewed;
                }
                private static void _IsTranslationReviewed_SetImplementationValue(global::LightSwitchApplication.common_developerlist_translate.DetailsClass d, global::System.Nullable<bool> v)
                {
                    d.ImplementationEntity.IsTranslationReviewed = v;
                }
                private static void _IsTranslationReviewed_OnValueChanged(global::LightSwitchApplication.common_developerlist_translate e)
                {
                    e.IsTranslationReviewed_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    DeletedOn = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "DeletedOn",
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._DeletedOn_Stub,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._DeletedOn_ComputeIsReadOnly,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._DeletedOn_Validate,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._DeletedOn_GetImplementationValue,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._DeletedOn_SetImplementationValue,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._DeletedOn_OnValueChanged);
                private static void _DeletedOn_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.common_developerlist_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._DeletedOn, sf);
                }
                private static bool _DeletedOn_ComputeIsReadOnly(global::LightSwitchApplication.common_developerlist_translate e)
                {
                    bool result = false;
                    e.DeletedOn_IsReadOnly(ref result);
                    return result;
                }
                private static void _DeletedOn_Validate(global::LightSwitchApplication.common_developerlist_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DeletedOn_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _DeletedOn_GetImplementationValue(global::LightSwitchApplication.common_developerlist_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.DeletedOn;
                }
                private static void _DeletedOn_SetImplementationValue(global::LightSwitchApplication.common_developerlist_translate.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.DeletedOn = global::LightSwitchApplication.common_developerlist_translate.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _DeletedOn_OnValueChanged(global::LightSwitchApplication.common_developerlist_translate e)
                {
                    e.DeletedOn_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::LightSwitchApplication.common_developerlist>.Entry
                    common_developerlist = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::LightSwitchApplication.common_developerlist>.Entry(
                        "common_developerlist",
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._common_developerlist_Stub,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._common_developerlist_ComputeIsReadOnly,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._common_developerlist_Validate,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._common_developerlist_GetCoreImplementationValue,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._common_developerlist_GetImplementationValue,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._common_developerlist_SetImplementationValue,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._common_developerlist_Refresh,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._common_developerlist_OnValueChanged);
                private static void _common_developerlist_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::LightSwitchApplication.common_developerlist>.Data> c, global::LightSwitchApplication.common_developerlist_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._common_developerlist, sf);
                }
                private static bool _common_developerlist_ComputeIsReadOnly(global::LightSwitchApplication.common_developerlist_translate e)
                {
                    bool result = false;
                    e.common_developerlist_IsReadOnly(ref result);
                    return result;
                }
                private static void _common_developerlist_Validate(global::LightSwitchApplication.common_developerlist_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.common_developerlist_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _common_developerlist_GetCoreImplementationValue(global::LightSwitchApplication.common_developerlist_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.common_developerlist;
                }
                private static global::LightSwitchApplication.common_developerlist _common_developerlist_GetImplementationValue(global::LightSwitchApplication.common_developerlist_translate.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.common_developerlist, global::LightSwitchApplication.common_developerlist.DetailsClass>(global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.common_developerlist, ref d._common_developerlist);
                }
                private static void _common_developerlist_SetImplementationValue(global::LightSwitchApplication.common_developerlist_translate.DetailsClass d, global::LightSwitchApplication.common_developerlist v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.common_developerlist, ref d._common_developerlist, (i, ev) => i.common_developerlist = ev, v);
                }
                private static void _common_developerlist_Refresh(global::LightSwitchApplication.common_developerlist_translate.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.common_developerlist, ref d._common_developerlist);
                }
                private static void _common_developerlist_OnValueChanged(global::LightSwitchApplication.common_developerlist_translate e)
                {
                    e.common_developerlist_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::LightSwitchApplication.vilani_language>.Entry
                    vilani_language1 = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::LightSwitchApplication.vilani_language>.Entry(
                        "vilani_language1",
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._vilani_language1_Stub,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._vilani_language1_ComputeIsReadOnly,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._vilani_language1_Validate,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._vilani_language1_GetCoreImplementationValue,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._vilani_language1_GetImplementationValue,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._vilani_language1_SetImplementationValue,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._vilani_language1_Refresh,
                        global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties._vilani_language1_OnValueChanged);
                private static void _vilani_language1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::LightSwitchApplication.vilani_language>.Data> c, global::LightSwitchApplication.common_developerlist_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._vilani_language1, sf);
                }
                private static bool _vilani_language1_ComputeIsReadOnly(global::LightSwitchApplication.common_developerlist_translate e)
                {
                    bool result = false;
                    e.vilani_language1_IsReadOnly(ref result);
                    return result;
                }
                private static void _vilani_language1_Validate(global::LightSwitchApplication.common_developerlist_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.vilani_language1_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _vilani_language1_GetCoreImplementationValue(global::LightSwitchApplication.common_developerlist_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.vilani_language1;
                }
                private static global::LightSwitchApplication.vilani_language _vilani_language1_GetImplementationValue(global::LightSwitchApplication.common_developerlist_translate.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass>(global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.vilani_language1, ref d._vilani_language1);
                }
                private static void _vilani_language1_SetImplementationValue(global::LightSwitchApplication.common_developerlist_translate.DetailsClass d, global::LightSwitchApplication.vilani_language v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.vilani_language1, ref d._vilani_language1, (i, ev) => i.vilani_language1 = ev, v);
                }
                private static void _vilani_language1_Refresh(global::LightSwitchApplication.common_developerlist_translate.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.common_developerlist_translate.DetailsClass.PropertySetProperties.vilani_language1, ref d._vilani_language1);
                }
                private static void _vilani_language1_OnValueChanged(global::LightSwitchApplication.common_developerlist_translate e)
                {
                    e.vilani_language1_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, int>.Data _DeveloperTranslateID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, string>.Data _DeveloperName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, string>.Data _CompanyName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, string>.Data _AboutUs;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, string>.Data _ContactPersonName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, string>.Data _Description;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _CreateDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _ModifiedDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::System.Nullable<bool>>.Data _IsTranslationReviewed;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _DeletedOn;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::LightSwitchApplication.common_developerlist>.Data _common_developerlist;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass, global::LightSwitchApplication.vilani_language>.Data _vilani_language1;
            
        }
    
        #endregion
    }
    
    #endregion
}
