

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class plot_plotowner_translate : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the plot_plotowner_translate entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public plot_plotowner_translate()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public plot_plotowner_translate(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.plot_plotowner_translate> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void plot_plotowner_translate_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void plot_plotowner_translate_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int PlotOwnerTranslateID
        {
            get
            {
                return global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.PlotOwnerTranslateID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PlotOwnerTranslateID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PlotOwnerTranslateID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PlotOwnerTranslateID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string FirstName
        {
            get
            {
                return global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.FirstName);
            }
            set
            {
                global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.FirstName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FirstName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FirstName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FirstName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string MiddleName
        {
            get
            {
                return global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.MiddleName);
            }
            set
            {
                global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.MiddleName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MiddleName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MiddleName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MiddleName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string LastName
        {
            get
            {
                return global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.LastName);
            }
            set
            {
                global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.LastName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LastName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LastName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LastName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string AddressLine1
        {
            get
            {
                return global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.AddressLine1);
            }
            set
            {
                global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.AddressLine1, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AddressLine1_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AddressLine1_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AddressLine1_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string AddressLine2
        {
            get
            {
                return global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.AddressLine2);
            }
            set
            {
                global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.AddressLine2, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AddressLine2_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AddressLine2_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AddressLine2_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<bool> IsTranslationReviewed
        {
            get
            {
                return global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.IsTranslationReviewed);
            }
            set
            {
                global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.IsTranslationReviewed, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsTranslationReviewed_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsTranslationReviewed_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsTranslationReviewed_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.ModifiedDate);
            }
            set
            {
                global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.ModifiedDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.vilani_language vilani_language1
        {
            get
            {
                return global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.vilani_language1);
            }
            set
            {
                global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.vilani_language1, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void vilani_language1_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void vilani_language1_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void vilani_language1_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.plot_plotowner plot_plotowner
        {
            get
            {
                return global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.plot_plotowner);
            }
            set
            {
                global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.plot_plotowner, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void plot_plotowner_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void plot_plotowner_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void plot_plotowner_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.plot_plotowner_translate,
                global::LightSwitchApplication.plot_plotowner_translate.DetailsClass,
                global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.IImplementation,
                global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.PlotOwnerTranslateID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass>.Entry
                __plot_plotowner_translateEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass>.Entry(
                    global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.__plot_plotowner_translate_CreateNew,
                    global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.__plot_plotowner_translate_Created,
                    global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.__plot_plotowner_translate_AllowSaveWithErrors);
            private static global::LightSwitchApplication.plot_plotowner_translate __plot_plotowner_translate_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.plot_plotowner_translate> es)
            {
                return new global::LightSwitchApplication.plot_plotowner_translate(es);
            }
            private static void __plot_plotowner_translate_Created(global::LightSwitchApplication.plot_plotowner_translate e)
            {
                e.plot_plotowner_translate_Created();
            }
            private static bool __plot_plotowner_translate_AllowSaveWithErrors(global::LightSwitchApplication.plot_plotowner_translate e)
            {
                bool result = false;
                e.plot_plotowner_translate_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, int> PlotOwnerTranslateID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.PlotOwnerTranslateID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, string> FirstName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.FirstName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, string> MiddleName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.MiddleName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, string> LastName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.LastName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, string> AddressLine1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.AddressLine1) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, string> AddressLine2
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.AddressLine2) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::System.Nullable<bool>> IsTranslationReviewed
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.IsTranslationReviewed) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::System.Nullable<bool>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::System.Nullable<global::System.DateTime>> ModifiedDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.ModifiedDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::LightSwitchApplication.vilani_language> vilani_language1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.vilani_language1) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::LightSwitchApplication.vilani_language>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::LightSwitchApplication.plot_plotowner> plot_plotowner
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.plot_plotowner) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::LightSwitchApplication.plot_plotowner>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int PlotOwnerTranslateID { get; }
                new string FirstName { get; set; }
                new string MiddleName { get; set; }
                new string LastName { get; set; }
                new string AddressLine1 { get; set; }
                new string AddressLine2 { get; set; }
                new global::System.Nullable<bool> IsTranslationReviewed { get; set; }
                new global::System.Nullable<global::System.DateTime> ModifiedDate { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation vilani_language1 { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation plot_plotowner { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, int>.Entry
                    PlotOwnerTranslateID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, int>.Entry(
                        "PlotOwnerTranslateID",
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._PlotOwnerTranslateID_Stub,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._PlotOwnerTranslateID_ComputeIsReadOnly,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._PlotOwnerTranslateID_Validate,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._PlotOwnerTranslateID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._PlotOwnerTranslateID_OnValueChanged);
                private static void _PlotOwnerTranslateID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, int>.Data> c, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._PlotOwnerTranslateID, sf);
                }
                private static bool _PlotOwnerTranslateID_ComputeIsReadOnly(global::LightSwitchApplication.plot_plotowner_translate e)
                {
                    bool result = false;
                    e.PlotOwnerTranslateID_IsReadOnly(ref result);
                    return result;
                }
                private static void _PlotOwnerTranslateID_Validate(global::LightSwitchApplication.plot_plotowner_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PlotOwnerTranslateID_Validate(r);
                }
                private static int _PlotOwnerTranslateID_GetImplementationValue(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.PlotOwnerTranslateID;
                }
                private static void _PlotOwnerTranslateID_OnValueChanged(global::LightSwitchApplication.plot_plotowner_translate e)
                {
                    e.PlotOwnerTranslateID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, string>.Entry
                    FirstName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, string>.Entry(
                        "FirstName",
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._FirstName_Stub,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._FirstName_ComputeIsReadOnly,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._FirstName_Validate,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._FirstName_GetImplementationValue,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._FirstName_SetImplementationValue,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._FirstName_OnValueChanged);
                private static void _FirstName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, string>.Data> c, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._FirstName, sf);
                }
                private static bool _FirstName_ComputeIsReadOnly(global::LightSwitchApplication.plot_plotowner_translate e)
                {
                    bool result = false;
                    e.FirstName_IsReadOnly(ref result);
                    return result;
                }
                private static void _FirstName_Validate(global::LightSwitchApplication.plot_plotowner_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.FirstName_Validate(r);
                }
                private static string _FirstName_GetImplementationValue(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.FirstName;
                }
                private static void _FirstName_SetImplementationValue(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass d, string v)
                {
                    d.ImplementationEntity.FirstName = v;
                }
                private static void _FirstName_OnValueChanged(global::LightSwitchApplication.plot_plotowner_translate e)
                {
                    e.FirstName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, string>.Entry
                    MiddleName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, string>.Entry(
                        "MiddleName",
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._MiddleName_Stub,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._MiddleName_ComputeIsReadOnly,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._MiddleName_Validate,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._MiddleName_GetImplementationValue,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._MiddleName_SetImplementationValue,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._MiddleName_OnValueChanged);
                private static void _MiddleName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, string>.Data> c, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._MiddleName, sf);
                }
                private static bool _MiddleName_ComputeIsReadOnly(global::LightSwitchApplication.plot_plotowner_translate e)
                {
                    bool result = false;
                    e.MiddleName_IsReadOnly(ref result);
                    return result;
                }
                private static void _MiddleName_Validate(global::LightSwitchApplication.plot_plotowner_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.MiddleName_Validate(r);
                }
                private static string _MiddleName_GetImplementationValue(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.MiddleName;
                }
                private static void _MiddleName_SetImplementationValue(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass d, string v)
                {
                    d.ImplementationEntity.MiddleName = v;
                }
                private static void _MiddleName_OnValueChanged(global::LightSwitchApplication.plot_plotowner_translate e)
                {
                    e.MiddleName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, string>.Entry
                    LastName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, string>.Entry(
                        "LastName",
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._LastName_Stub,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._LastName_ComputeIsReadOnly,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._LastName_Validate,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._LastName_GetImplementationValue,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._LastName_SetImplementationValue,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._LastName_OnValueChanged);
                private static void _LastName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, string>.Data> c, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._LastName, sf);
                }
                private static bool _LastName_ComputeIsReadOnly(global::LightSwitchApplication.plot_plotowner_translate e)
                {
                    bool result = false;
                    e.LastName_IsReadOnly(ref result);
                    return result;
                }
                private static void _LastName_Validate(global::LightSwitchApplication.plot_plotowner_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.LastName_Validate(r);
                }
                private static string _LastName_GetImplementationValue(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.LastName;
                }
                private static void _LastName_SetImplementationValue(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass d, string v)
                {
                    d.ImplementationEntity.LastName = v;
                }
                private static void _LastName_OnValueChanged(global::LightSwitchApplication.plot_plotowner_translate e)
                {
                    e.LastName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, string>.Entry
                    AddressLine1 = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, string>.Entry(
                        "AddressLine1",
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._AddressLine1_Stub,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._AddressLine1_ComputeIsReadOnly,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._AddressLine1_Validate,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._AddressLine1_GetImplementationValue,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._AddressLine1_SetImplementationValue,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._AddressLine1_OnValueChanged);
                private static void _AddressLine1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, string>.Data> c, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._AddressLine1, sf);
                }
                private static bool _AddressLine1_ComputeIsReadOnly(global::LightSwitchApplication.plot_plotowner_translate e)
                {
                    bool result = false;
                    e.AddressLine1_IsReadOnly(ref result);
                    return result;
                }
                private static void _AddressLine1_Validate(global::LightSwitchApplication.plot_plotowner_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.AddressLine1_Validate(r);
                }
                private static string _AddressLine1_GetImplementationValue(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.AddressLine1;
                }
                private static void _AddressLine1_SetImplementationValue(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass d, string v)
                {
                    d.ImplementationEntity.AddressLine1 = v;
                }
                private static void _AddressLine1_OnValueChanged(global::LightSwitchApplication.plot_plotowner_translate e)
                {
                    e.AddressLine1_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, string>.Entry
                    AddressLine2 = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, string>.Entry(
                        "AddressLine2",
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._AddressLine2_Stub,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._AddressLine2_ComputeIsReadOnly,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._AddressLine2_Validate,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._AddressLine2_GetImplementationValue,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._AddressLine2_SetImplementationValue,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._AddressLine2_OnValueChanged);
                private static void _AddressLine2_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, string>.Data> c, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._AddressLine2, sf);
                }
                private static bool _AddressLine2_ComputeIsReadOnly(global::LightSwitchApplication.plot_plotowner_translate e)
                {
                    bool result = false;
                    e.AddressLine2_IsReadOnly(ref result);
                    return result;
                }
                private static void _AddressLine2_Validate(global::LightSwitchApplication.plot_plotowner_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.AddressLine2_Validate(r);
                }
                private static string _AddressLine2_GetImplementationValue(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.AddressLine2;
                }
                private static void _AddressLine2_SetImplementationValue(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass d, string v)
                {
                    d.ImplementationEntity.AddressLine2 = v;
                }
                private static void _AddressLine2_OnValueChanged(global::LightSwitchApplication.plot_plotowner_translate e)
                {
                    e.AddressLine2_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::System.Nullable<bool>>.Entry
                    IsTranslationReviewed = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::System.Nullable<bool>>.Entry(
                        "IsTranslationReviewed",
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._IsTranslationReviewed_Stub,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._IsTranslationReviewed_ComputeIsReadOnly,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._IsTranslationReviewed_Validate,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._IsTranslationReviewed_GetImplementationValue,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._IsTranslationReviewed_SetImplementationValue,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._IsTranslationReviewed_OnValueChanged);
                private static void _IsTranslationReviewed_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::System.Nullable<bool>>.Data> c, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._IsTranslationReviewed, sf);
                }
                private static bool _IsTranslationReviewed_ComputeIsReadOnly(global::LightSwitchApplication.plot_plotowner_translate e)
                {
                    bool result = false;
                    e.IsTranslationReviewed_IsReadOnly(ref result);
                    return result;
                }
                private static void _IsTranslationReviewed_Validate(global::LightSwitchApplication.plot_plotowner_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.IsTranslationReviewed_Validate(r);
                }
                private static global::System.Nullable<bool> _IsTranslationReviewed_GetImplementationValue(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.IsTranslationReviewed;
                }
                private static void _IsTranslationReviewed_SetImplementationValue(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass d, global::System.Nullable<bool> v)
                {
                    d.ImplementationEntity.IsTranslationReviewed = v;
                }
                private static void _IsTranslationReviewed_OnValueChanged(global::LightSwitchApplication.plot_plotowner_translate e)
                {
                    e.IsTranslationReviewed_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    ModifiedDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "ModifiedDate",
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._ModifiedDate_Stub,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._ModifiedDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._ModifiedDate_Validate,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._ModifiedDate_GetImplementationValue,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._ModifiedDate_SetImplementationValue,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._ModifiedDate_OnValueChanged);
                private static void _ModifiedDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedDate, sf);
                }
                private static bool _ModifiedDate_ComputeIsReadOnly(global::LightSwitchApplication.plot_plotowner_translate e)
                {
                    bool result = false;
                    e.ModifiedDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedDate_Validate(global::LightSwitchApplication.plot_plotowner_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _ModifiedDate_GetImplementationValue(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedDate;
                }
                private static void _ModifiedDate_SetImplementationValue(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.ModifiedDate = global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _ModifiedDate_OnValueChanged(global::LightSwitchApplication.plot_plotowner_translate e)
                {
                    e.ModifiedDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::LightSwitchApplication.vilani_language>.Entry
                    vilani_language1 = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::LightSwitchApplication.vilani_language>.Entry(
                        "vilani_language1",
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._vilani_language1_Stub,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._vilani_language1_ComputeIsReadOnly,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._vilani_language1_Validate,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._vilani_language1_GetCoreImplementationValue,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._vilani_language1_GetImplementationValue,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._vilani_language1_SetImplementationValue,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._vilani_language1_Refresh,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._vilani_language1_OnValueChanged);
                private static void _vilani_language1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::LightSwitchApplication.vilani_language>.Data> c, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._vilani_language1, sf);
                }
                private static bool _vilani_language1_ComputeIsReadOnly(global::LightSwitchApplication.plot_plotowner_translate e)
                {
                    bool result = false;
                    e.vilani_language1_IsReadOnly(ref result);
                    return result;
                }
                private static void _vilani_language1_Validate(global::LightSwitchApplication.plot_plotowner_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.vilani_language1_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _vilani_language1_GetCoreImplementationValue(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.vilani_language1;
                }
                private static global::LightSwitchApplication.vilani_language _vilani_language1_GetImplementationValue(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass>(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.vilani_language1, ref d._vilani_language1);
                }
                private static void _vilani_language1_SetImplementationValue(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass d, global::LightSwitchApplication.vilani_language v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.vilani_language1, ref d._vilani_language1, (i, ev) => i.vilani_language1 = ev, v);
                }
                private static void _vilani_language1_Refresh(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.vilani_language1, ref d._vilani_language1);
                }
                private static void _vilani_language1_OnValueChanged(global::LightSwitchApplication.plot_plotowner_translate e)
                {
                    e.vilani_language1_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::LightSwitchApplication.plot_plotowner>.Entry
                    plot_plotowner = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::LightSwitchApplication.plot_plotowner>.Entry(
                        "plot_plotowner",
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._plot_plotowner_Stub,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._plot_plotowner_ComputeIsReadOnly,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._plot_plotowner_Validate,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._plot_plotowner_GetCoreImplementationValue,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._plot_plotowner_GetImplementationValue,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._plot_plotowner_SetImplementationValue,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._plot_plotowner_Refresh,
                        global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties._plot_plotowner_OnValueChanged);
                private static void _plot_plotowner_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::LightSwitchApplication.plot_plotowner>.Data> c, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._plot_plotowner, sf);
                }
                private static bool _plot_plotowner_ComputeIsReadOnly(global::LightSwitchApplication.plot_plotowner_translate e)
                {
                    bool result = false;
                    e.plot_plotowner_IsReadOnly(ref result);
                    return result;
                }
                private static void _plot_plotowner_Validate(global::LightSwitchApplication.plot_plotowner_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.plot_plotowner_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _plot_plotowner_GetCoreImplementationValue(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.plot_plotowner;
                }
                private static global::LightSwitchApplication.plot_plotowner _plot_plotowner_GetImplementationValue(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.plot_plotowner, global::LightSwitchApplication.plot_plotowner.DetailsClass>(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.plot_plotowner, ref d._plot_plotowner);
                }
                private static void _plot_plotowner_SetImplementationValue(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass d, global::LightSwitchApplication.plot_plotowner v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.plot_plotowner, ref d._plot_plotowner, (i, ev) => i.plot_plotowner = ev, v);
                }
                private static void _plot_plotowner_Refresh(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.plot_plotowner_translate.DetailsClass.PropertySetProperties.plot_plotowner, ref d._plot_plotowner);
                }
                private static void _plot_plotowner_OnValueChanged(global::LightSwitchApplication.plot_plotowner_translate e)
                {
                    e.plot_plotowner_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, int>.Data _PlotOwnerTranslateID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, string>.Data _FirstName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, string>.Data _MiddleName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, string>.Data _LastName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, string>.Data _AddressLine1;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, string>.Data _AddressLine2;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::System.Nullable<bool>>.Data _IsTranslationReviewed;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _ModifiedDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::LightSwitchApplication.vilani_language>.Data _vilani_language1;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass, global::LightSwitchApplication.plot_plotowner>.Data _plot_plotowner;
            
        }
    
        #endregion
    }
    
    #endregion
}
