

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class plot_plottingscheme_translate : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the plot_plottingscheme_translate entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public plot_plottingscheme_translate()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public plot_plottingscheme_translate(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.plot_plottingscheme_translate> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void plot_plottingscheme_translate_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void plot_plottingscheme_translate_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int PlottingSchemeTranslateID
        {
            get
            {
                return global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties.PlottingSchemeTranslateID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PlottingSchemeTranslateID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PlottingSchemeTranslateID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PlottingSchemeTranslateID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string SchemeName
        {
            get
            {
                return global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties.SchemeName);
            }
            set
            {
                global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties.SchemeName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SchemeName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SchemeName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SchemeName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string AboutScheme
        {
            get
            {
                return global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties.AboutScheme);
            }
            set
            {
                global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties.AboutScheme, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AboutScheme_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AboutScheme_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AboutScheme_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Description
        {
            get
            {
                return global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties.Description);
            }
            set
            {
                global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties.Description, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<bool> IsTranslationReviewed
        {
            get
            {
                return global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties.IsTranslationReviewed);
            }
            set
            {
                global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties.IsTranslationReviewed, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsTranslationReviewed_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsTranslationReviewed_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsTranslationReviewed_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties.ModifiedDate);
            }
            set
            {
                global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties.ModifiedDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> DeletedOn
        {
            get
            {
                return global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties.DeletedOn);
            }
            set
            {
                global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties.DeletedOn, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DeletedOn_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DeletedOn_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DeletedOn_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.plot_plottingscheme plot_plottingscheme
        {
            get
            {
                return global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties.plot_plottingscheme);
            }
            set
            {
                global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties.plot_plottingscheme, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void plot_plottingscheme_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void plot_plottingscheme_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void plot_plottingscheme_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.vilani_language vilani_language
        {
            get
            {
                return global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.GetValue(this, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties.vilani_language);
            }
            set
            {
                global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.SetValue(this, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties.vilani_language, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void vilani_language_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void vilani_language_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void vilani_language_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.plot_plottingscheme_translate,
                global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass,
                global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.IImplementation,
                global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties.PlottingSchemeTranslateID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass>.Entry
                __plot_plottingscheme_translateEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass>.Entry(
                    global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.__plot_plottingscheme_translate_CreateNew,
                    global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.__plot_plottingscheme_translate_Created,
                    global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.__plot_plottingscheme_translate_AllowSaveWithErrors);
            private static global::LightSwitchApplication.plot_plottingscheme_translate __plot_plottingscheme_translate_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.plot_plottingscheme_translate> es)
            {
                return new global::LightSwitchApplication.plot_plottingscheme_translate(es);
            }
            private static void __plot_plottingscheme_translate_Created(global::LightSwitchApplication.plot_plottingscheme_translate e)
            {
                e.plot_plottingscheme_translate_Created();
            }
            private static bool __plot_plottingscheme_translate_AllowSaveWithErrors(global::LightSwitchApplication.plot_plottingscheme_translate e)
            {
                bool result = false;
                e.plot_plottingscheme_translate_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, int> PlottingSchemeTranslateID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties.PlottingSchemeTranslateID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, string> SchemeName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties.SchemeName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, string> AboutScheme
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties.AboutScheme) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, string> Description
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties.Description) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::System.Nullable<bool>> IsTranslationReviewed
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties.IsTranslationReviewed) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::System.Nullable<bool>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::System.Nullable<global::System.DateTime>> ModifiedDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties.ModifiedDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::System.Nullable<global::System.DateTime>> DeletedOn
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties.DeletedOn) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::LightSwitchApplication.plot_plottingscheme> plot_plottingscheme
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties.plot_plottingscheme) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::LightSwitchApplication.plot_plottingscheme>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::LightSwitchApplication.vilani_language> vilani_language
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties.vilani_language) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::LightSwitchApplication.vilani_language>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int PlottingSchemeTranslateID { get; }
                new string SchemeName { get; set; }
                new string AboutScheme { get; set; }
                new string Description { get; set; }
                new global::System.Nullable<bool> IsTranslationReviewed { get; set; }
                new global::System.Nullable<global::System.DateTime> ModifiedDate { get; set; }
                new global::System.Nullable<global::System.DateTime> DeletedOn { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation plot_plottingscheme { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation vilani_language { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, int>.Entry
                    PlottingSchemeTranslateID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, int>.Entry(
                        "PlottingSchemeTranslateID",
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._PlottingSchemeTranslateID_Stub,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._PlottingSchemeTranslateID_ComputeIsReadOnly,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._PlottingSchemeTranslateID_Validate,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._PlottingSchemeTranslateID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._PlottingSchemeTranslateID_OnValueChanged);
                private static void _PlottingSchemeTranslateID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, int>.Data> c, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._PlottingSchemeTranslateID, sf);
                }
                private static bool _PlottingSchemeTranslateID_ComputeIsReadOnly(global::LightSwitchApplication.plot_plottingscheme_translate e)
                {
                    bool result = false;
                    e.PlottingSchemeTranslateID_IsReadOnly(ref result);
                    return result;
                }
                private static void _PlottingSchemeTranslateID_Validate(global::LightSwitchApplication.plot_plottingscheme_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PlottingSchemeTranslateID_Validate(r);
                }
                private static int _PlottingSchemeTranslateID_GetImplementationValue(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.PlottingSchemeTranslateID;
                }
                private static void _PlottingSchemeTranslateID_OnValueChanged(global::LightSwitchApplication.plot_plottingscheme_translate e)
                {
                    e.PlottingSchemeTranslateID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, string>.Entry
                    SchemeName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, string>.Entry(
                        "SchemeName",
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._SchemeName_Stub,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._SchemeName_ComputeIsReadOnly,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._SchemeName_Validate,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._SchemeName_GetImplementationValue,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._SchemeName_SetImplementationValue,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._SchemeName_OnValueChanged);
                private static void _SchemeName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, string>.Data> c, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._SchemeName, sf);
                }
                private static bool _SchemeName_ComputeIsReadOnly(global::LightSwitchApplication.plot_plottingscheme_translate e)
                {
                    bool result = false;
                    e.SchemeName_IsReadOnly(ref result);
                    return result;
                }
                private static void _SchemeName_Validate(global::LightSwitchApplication.plot_plottingscheme_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.SchemeName_Validate(r);
                }
                private static string _SchemeName_GetImplementationValue(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.SchemeName;
                }
                private static void _SchemeName_SetImplementationValue(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass d, string v)
                {
                    d.ImplementationEntity.SchemeName = v;
                }
                private static void _SchemeName_OnValueChanged(global::LightSwitchApplication.plot_plottingscheme_translate e)
                {
                    e.SchemeName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, string>.Entry
                    AboutScheme = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, string>.Entry(
                        "AboutScheme",
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._AboutScheme_Stub,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._AboutScheme_ComputeIsReadOnly,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._AboutScheme_Validate,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._AboutScheme_GetImplementationValue,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._AboutScheme_SetImplementationValue,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._AboutScheme_OnValueChanged);
                private static void _AboutScheme_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, string>.Data> c, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._AboutScheme, sf);
                }
                private static bool _AboutScheme_ComputeIsReadOnly(global::LightSwitchApplication.plot_plottingscheme_translate e)
                {
                    bool result = false;
                    e.AboutScheme_IsReadOnly(ref result);
                    return result;
                }
                private static void _AboutScheme_Validate(global::LightSwitchApplication.plot_plottingscheme_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.AboutScheme_Validate(r);
                }
                private static string _AboutScheme_GetImplementationValue(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.AboutScheme;
                }
                private static void _AboutScheme_SetImplementationValue(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass d, string v)
                {
                    d.ImplementationEntity.AboutScheme = v;
                }
                private static void _AboutScheme_OnValueChanged(global::LightSwitchApplication.plot_plottingscheme_translate e)
                {
                    e.AboutScheme_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, string>.Entry
                    Description = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, string>.Entry(
                        "Description",
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._Description_Stub,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._Description_ComputeIsReadOnly,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._Description_Validate,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._Description_GetImplementationValue,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._Description_SetImplementationValue,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._Description_OnValueChanged);
                private static void _Description_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, string>.Data> c, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._Description, sf);
                }
                private static bool _Description_ComputeIsReadOnly(global::LightSwitchApplication.plot_plottingscheme_translate e)
                {
                    bool result = false;
                    e.Description_IsReadOnly(ref result);
                    return result;
                }
                private static void _Description_Validate(global::LightSwitchApplication.plot_plottingscheme_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Description_Validate(r);
                }
                private static string _Description_GetImplementationValue(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.Description;
                }
                private static void _Description_SetImplementationValue(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Description = v;
                }
                private static void _Description_OnValueChanged(global::LightSwitchApplication.plot_plottingscheme_translate e)
                {
                    e.Description_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::System.Nullable<bool>>.Entry
                    IsTranslationReviewed = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::System.Nullable<bool>>.Entry(
                        "IsTranslationReviewed",
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._IsTranslationReviewed_Stub,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._IsTranslationReviewed_ComputeIsReadOnly,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._IsTranslationReviewed_Validate,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._IsTranslationReviewed_GetImplementationValue,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._IsTranslationReviewed_SetImplementationValue,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._IsTranslationReviewed_OnValueChanged);
                private static void _IsTranslationReviewed_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::System.Nullable<bool>>.Data> c, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._IsTranslationReviewed, sf);
                }
                private static bool _IsTranslationReviewed_ComputeIsReadOnly(global::LightSwitchApplication.plot_plottingscheme_translate e)
                {
                    bool result = false;
                    e.IsTranslationReviewed_IsReadOnly(ref result);
                    return result;
                }
                private static void _IsTranslationReviewed_Validate(global::LightSwitchApplication.plot_plottingscheme_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.IsTranslationReviewed_Validate(r);
                }
                private static global::System.Nullable<bool> _IsTranslationReviewed_GetImplementationValue(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.IsTranslationReviewed;
                }
                private static void _IsTranslationReviewed_SetImplementationValue(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass d, global::System.Nullable<bool> v)
                {
                    d.ImplementationEntity.IsTranslationReviewed = v;
                }
                private static void _IsTranslationReviewed_OnValueChanged(global::LightSwitchApplication.plot_plottingscheme_translate e)
                {
                    e.IsTranslationReviewed_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    ModifiedDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "ModifiedDate",
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._ModifiedDate_Stub,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._ModifiedDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._ModifiedDate_Validate,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._ModifiedDate_GetImplementationValue,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._ModifiedDate_SetImplementationValue,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._ModifiedDate_OnValueChanged);
                private static void _ModifiedDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedDate, sf);
                }
                private static bool _ModifiedDate_ComputeIsReadOnly(global::LightSwitchApplication.plot_plottingscheme_translate e)
                {
                    bool result = false;
                    e.ModifiedDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedDate_Validate(global::LightSwitchApplication.plot_plottingscheme_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _ModifiedDate_GetImplementationValue(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedDate;
                }
                private static void _ModifiedDate_SetImplementationValue(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.ModifiedDate = global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _ModifiedDate_OnValueChanged(global::LightSwitchApplication.plot_plottingscheme_translate e)
                {
                    e.ModifiedDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    DeletedOn = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "DeletedOn",
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._DeletedOn_Stub,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._DeletedOn_ComputeIsReadOnly,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._DeletedOn_Validate,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._DeletedOn_GetImplementationValue,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._DeletedOn_SetImplementationValue,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._DeletedOn_OnValueChanged);
                private static void _DeletedOn_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._DeletedOn, sf);
                }
                private static bool _DeletedOn_ComputeIsReadOnly(global::LightSwitchApplication.plot_plottingscheme_translate e)
                {
                    bool result = false;
                    e.DeletedOn_IsReadOnly(ref result);
                    return result;
                }
                private static void _DeletedOn_Validate(global::LightSwitchApplication.plot_plottingscheme_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DeletedOn_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _DeletedOn_GetImplementationValue(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.DeletedOn;
                }
                private static void _DeletedOn_SetImplementationValue(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.DeletedOn = global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _DeletedOn_OnValueChanged(global::LightSwitchApplication.plot_plottingscheme_translate e)
                {
                    e.DeletedOn_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::LightSwitchApplication.plot_plottingscheme>.Entry
                    plot_plottingscheme = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::LightSwitchApplication.plot_plottingscheme>.Entry(
                        "plot_plottingscheme",
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._plot_plottingscheme_Stub,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._plot_plottingscheme_ComputeIsReadOnly,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._plot_plottingscheme_Validate,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._plot_plottingscheme_GetCoreImplementationValue,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._plot_plottingscheme_GetImplementationValue,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._plot_plottingscheme_SetImplementationValue,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._plot_plottingscheme_Refresh,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._plot_plottingscheme_OnValueChanged);
                private static void _plot_plottingscheme_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::LightSwitchApplication.plot_plottingscheme>.Data> c, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._plot_plottingscheme, sf);
                }
                private static bool _plot_plottingscheme_ComputeIsReadOnly(global::LightSwitchApplication.plot_plottingscheme_translate e)
                {
                    bool result = false;
                    e.plot_plottingscheme_IsReadOnly(ref result);
                    return result;
                }
                private static void _plot_plottingscheme_Validate(global::LightSwitchApplication.plot_plottingscheme_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.plot_plottingscheme_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _plot_plottingscheme_GetCoreImplementationValue(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.plot_plottingscheme;
                }
                private static global::LightSwitchApplication.plot_plottingscheme _plot_plottingscheme_GetImplementationValue(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.plot_plottingscheme, global::LightSwitchApplication.plot_plottingscheme.DetailsClass>(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties.plot_plottingscheme, ref d._plot_plottingscheme);
                }
                private static void _plot_plottingscheme_SetImplementationValue(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass d, global::LightSwitchApplication.plot_plottingscheme v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties.plot_plottingscheme, ref d._plot_plottingscheme, (i, ev) => i.plot_plottingscheme = ev, v);
                }
                private static void _plot_plottingscheme_Refresh(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties.plot_plottingscheme, ref d._plot_plottingscheme);
                }
                private static void _plot_plottingscheme_OnValueChanged(global::LightSwitchApplication.plot_plottingscheme_translate e)
                {
                    e.plot_plottingscheme_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::LightSwitchApplication.vilani_language>.Entry
                    vilani_language = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::LightSwitchApplication.vilani_language>.Entry(
                        "vilani_language",
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._vilani_language_Stub,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._vilani_language_ComputeIsReadOnly,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._vilani_language_Validate,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._vilani_language_GetCoreImplementationValue,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._vilani_language_GetImplementationValue,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._vilani_language_SetImplementationValue,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._vilani_language_Refresh,
                        global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties._vilani_language_OnValueChanged);
                private static void _vilani_language_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::LightSwitchApplication.vilani_language>.Data> c, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass d, object sf)
                {
                    c(d, ref d._vilani_language, sf);
                }
                private static bool _vilani_language_ComputeIsReadOnly(global::LightSwitchApplication.plot_plottingscheme_translate e)
                {
                    bool result = false;
                    e.vilani_language_IsReadOnly(ref result);
                    return result;
                }
                private static void _vilani_language_Validate(global::LightSwitchApplication.plot_plottingscheme_translate e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.vilani_language_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _vilani_language_GetCoreImplementationValue(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass d)
                {
                    return d.ImplementationEntity.vilani_language;
                }
                private static global::LightSwitchApplication.vilani_language _vilani_language_GetImplementationValue(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass>(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties.vilani_language, ref d._vilani_language);
                }
                private static void _vilani_language_SetImplementationValue(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass d, global::LightSwitchApplication.vilani_language v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties.vilani_language, ref d._vilani_language, (i, ev) => i.vilani_language = ev, v);
                }
                private static void _vilani_language_Refresh(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass.PropertySetProperties.vilani_language, ref d._vilani_language);
                }
                private static void _vilani_language_OnValueChanged(global::LightSwitchApplication.plot_plottingscheme_translate e)
                {
                    e.vilani_language_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, int>.Data _PlottingSchemeTranslateID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, string>.Data _SchemeName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, string>.Data _AboutScheme;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, string>.Data _Description;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::System.Nullable<bool>>.Data _IsTranslationReviewed;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _ModifiedDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _DeletedOn;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::LightSwitchApplication.plot_plottingscheme>.Data _plot_plottingscheme;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass, global::LightSwitchApplication.vilani_language>.Data _vilani_language;
            
        }
    
        #endregion
    }
    
    #endregion
}
