

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class vilani_language : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the vilani_language entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public vilani_language()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public vilani_language(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.vilani_language> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.vilani_language.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void vilani_language_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void vilani_language_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int LanguageID
        {
            get
            {
                return global::LightSwitchApplication.vilani_language.DetailsClass.GetValue(this, global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.LanguageID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LanguageID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LanguageID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LanguageID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string LanguageName
        {
            get
            {
                return global::LightSwitchApplication.vilani_language.DetailsClass.GetValue(this, global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.LanguageName);
            }
            set
            {
                global::LightSwitchApplication.vilani_language.DetailsClass.SetValue(this, global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.LanguageName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LanguageName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LanguageName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LanguageName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Description1
        {
            get
            {
                return global::LightSwitchApplication.vilani_language.DetailsClass.GetValue(this, global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.Description1);
            }
            set
            {
                global::LightSwitchApplication.vilani_language.DetailsClass.SetValue(this, global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.Description1, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description1_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description1_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description1_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.common_developerlist> common_developerlists
        {
            get
            {
                return global::LightSwitchApplication.vilani_language.DetailsClass.GetValue(this, global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.common_developerlists);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.common_developerlist> common_developerlistsQuery
        {
            get
            {
                return global::LightSwitchApplication.vilani_language.DetailsClass.GetQuery(this, global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.common_developerlists);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.common_officeaddress> common_officeaddresses
        {
            get
            {
                return global::LightSwitchApplication.vilani_language.DetailsClass.GetValue(this, global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.common_officeaddresses);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.common_officeaddress> common_officeaddressesQuery
        {
            get
            {
                return global::LightSwitchApplication.vilani_language.DetailsClass.GetQuery(this, global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.common_officeaddresses);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.common_officeaddress_translate> common_officeaddress_translates
        {
            get
            {
                return global::LightSwitchApplication.vilani_language.DetailsClass.GetValue(this, global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.common_officeaddress_translates);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.common_officeaddress_translate> common_officeaddress_translatesQuery
        {
            get
            {
                return global::LightSwitchApplication.vilani_language.DetailsClass.GetQuery(this, global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.common_officeaddress_translates);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.plot_plottingaddress> plot_plottingaddresses
        {
            get
            {
                return global::LightSwitchApplication.vilani_language.DetailsClass.GetValue(this, global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.plot_plottingaddresses);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.plot_plottingaddress> plot_plottingaddressesQuery
        {
            get
            {
                return global::LightSwitchApplication.vilani_language.DetailsClass.GetQuery(this, global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.plot_plottingaddresses);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.plot_plottingaddress_translate> plot_plottingaddress_translates
        {
            get
            {
                return global::LightSwitchApplication.vilani_language.DetailsClass.GetValue(this, global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.plot_plottingaddress_translates);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.plot_plottingaddress_translate> plot_plottingaddress_translatesQuery
        {
            get
            {
                return global::LightSwitchApplication.vilani_language.DetailsClass.GetQuery(this, global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.plot_plottingaddress_translates);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.plot_plottingscheme_translate> plot_plottingscheme_translates
        {
            get
            {
                return global::LightSwitchApplication.vilani_language.DetailsClass.GetValue(this, global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.plot_plottingscheme_translates);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.plot_plottingscheme_translate> plot_plottingscheme_translatesQuery
        {
            get
            {
                return global::LightSwitchApplication.vilani_language.DetailsClass.GetQuery(this, global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.plot_plottingscheme_translates);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.realestate_property> realestate_properties
        {
            get
            {
                return global::LightSwitchApplication.vilani_language.DetailsClass.GetValue(this, global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.realestate_properties);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.realestate_property> realestate_propertiesQuery
        {
            get
            {
                return global::LightSwitchApplication.vilani_language.DetailsClass.GetQuery(this, global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.realestate_properties);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.realestate_property_translate> realestate_property_translates
        {
            get
            {
                return global::LightSwitchApplication.vilani_language.DetailsClass.GetValue(this, global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.realestate_property_translates);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.realestate_property_translate> realestate_property_translatesQuery
        {
            get
            {
                return global::LightSwitchApplication.vilani_language.DetailsClass.GetQuery(this, global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.realestate_property_translates);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.common_developerlist_translate> common_developerlist_translates
        {
            get
            {
                return global::LightSwitchApplication.vilani_language.DetailsClass.GetValue(this, global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.common_developerlist_translates);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.common_developerlist_translate> common_developerlist_translatesQuery
        {
            get
            {
                return global::LightSwitchApplication.vilani_language.DetailsClass.GetQuery(this, global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.common_developerlist_translates);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.common_propertycontactperson_translate> common_propertycontactperson_translates
        {
            get
            {
                return global::LightSwitchApplication.vilani_language.DetailsClass.GetValue(this, global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.common_propertycontactperson_translates);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.common_propertycontactperson_translate> common_propertycontactperson_translatesQuery
        {
            get
            {
                return global::LightSwitchApplication.vilani_language.DetailsClass.GetQuery(this, global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.common_propertycontactperson_translates);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.plot_plotowner_translate> plot_plotowner_translates
        {
            get
            {
                return global::LightSwitchApplication.vilani_language.DetailsClass.GetValue(this, global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.plot_plotowner_translates);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.plot_plotowner_translate> plot_plotowner_translatesQuery
        {
            get
            {
                return global::LightSwitchApplication.vilani_language.DetailsClass.GetQuery(this, global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.plot_plotowner_translates);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.vilani_language,
                global::LightSwitchApplication.vilani_language.DetailsClass,
                global::LightSwitchApplication.vilani_language.DetailsClass.IImplementation,
                global::LightSwitchApplication.vilani_language.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.LanguageID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass>.Entry
                __vilani_languageEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass>.Entry(
                    global::LightSwitchApplication.vilani_language.DetailsClass.__vilani_language_CreateNew,
                    global::LightSwitchApplication.vilani_language.DetailsClass.__vilani_language_Created,
                    global::LightSwitchApplication.vilani_language.DetailsClass.__vilani_language_AllowSaveWithErrors);
            private static global::LightSwitchApplication.vilani_language __vilani_language_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.vilani_language> es)
            {
                return new global::LightSwitchApplication.vilani_language(es);
            }
            private static void __vilani_language_Created(global::LightSwitchApplication.vilani_language e)
            {
                e.vilani_language_Created();
            }
            private static bool __vilani_language_AllowSaveWithErrors(global::LightSwitchApplication.vilani_language e)
            {
                bool result = false;
                e.vilani_language_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.vilani_language.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, int> LanguageID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.LanguageID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, string> LanguageName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.LanguageName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, string> Description1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.Description1) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.common_developerlist> common_developerlists
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.common_developerlists) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.common_developerlist>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.common_officeaddress> common_officeaddresses
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.common_officeaddresses) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.common_officeaddress>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.common_officeaddress_translate> common_officeaddress_translates
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.common_officeaddress_translates) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.common_officeaddress_translate>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.plot_plottingaddress> plot_plottingaddresses
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.plot_plottingaddresses) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.plot_plottingaddress>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.plot_plottingaddress_translate> plot_plottingaddress_translates
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.plot_plottingaddress_translates) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.plot_plottingaddress_translate>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.plot_plottingscheme_translate> plot_plottingscheme_translates
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.plot_plottingscheme_translates) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.plot_plottingscheme_translate>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.realestate_property> realestate_properties
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.realestate_properties) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.realestate_property>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.realestate_property_translate> realestate_property_translates
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.realestate_property_translates) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.realestate_property_translate>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.common_developerlist_translate> common_developerlist_translates
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.common_developerlist_translates) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.common_developerlist_translate>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.common_propertycontactperson_translate> common_propertycontactperson_translates
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.common_propertycontactperson_translates) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.common_propertycontactperson_translate>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.plot_plotowner_translate> plot_plotowner_translates
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.plot_plotowner_translates) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.plot_plotowner_translate>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int LanguageID { get; }
                new string LanguageName { get; set; }
                new string Description1 { get; set; }
                new global::System.Collections.IEnumerable common_developerlists { get; }
                new global::System.Collections.IEnumerable common_officeaddresses { get; }
                new global::System.Collections.IEnumerable common_officeaddress_translates { get; }
                new global::System.Collections.IEnumerable plot_plottingaddresses { get; }
                new global::System.Collections.IEnumerable plot_plottingaddress_translates { get; }
                new global::System.Collections.IEnumerable plot_plottingscheme_translates { get; }
                new global::System.Collections.IEnumerable realestate_properties { get; }
                new global::System.Collections.IEnumerable realestate_property_translates { get; }
                new global::System.Collections.IEnumerable common_developerlist_translates { get; }
                new global::System.Collections.IEnumerable common_propertycontactperson_translates { get; }
                new global::System.Collections.IEnumerable plot_plotowner_translates { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, int>.Entry
                    LanguageID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, int>.Entry(
                        "LanguageID",
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._LanguageID_Stub,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._LanguageID_ComputeIsReadOnly,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._LanguageID_Validate,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._LanguageID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._LanguageID_OnValueChanged);
                private static void _LanguageID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.vilani_language.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, int>.Data> c, global::LightSwitchApplication.vilani_language.DetailsClass d, object sf)
                {
                    c(d, ref d._LanguageID, sf);
                }
                private static bool _LanguageID_ComputeIsReadOnly(global::LightSwitchApplication.vilani_language e)
                {
                    bool result = false;
                    e.LanguageID_IsReadOnly(ref result);
                    return result;
                }
                private static void _LanguageID_Validate(global::LightSwitchApplication.vilani_language e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.LanguageID_Validate(r);
                }
                private static int _LanguageID_GetImplementationValue(global::LightSwitchApplication.vilani_language.DetailsClass d)
                {
                    return d.ImplementationEntity.LanguageID;
                }
                private static void _LanguageID_OnValueChanged(global::LightSwitchApplication.vilani_language e)
                {
                    e.LanguageID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, string>.Entry
                    LanguageName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, string>.Entry(
                        "LanguageName",
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._LanguageName_Stub,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._LanguageName_ComputeIsReadOnly,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._LanguageName_Validate,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._LanguageName_GetImplementationValue,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._LanguageName_SetImplementationValue,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._LanguageName_OnValueChanged);
                private static void _LanguageName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.vilani_language.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, string>.Data> c, global::LightSwitchApplication.vilani_language.DetailsClass d, object sf)
                {
                    c(d, ref d._LanguageName, sf);
                }
                private static bool _LanguageName_ComputeIsReadOnly(global::LightSwitchApplication.vilani_language e)
                {
                    bool result = false;
                    e.LanguageName_IsReadOnly(ref result);
                    return result;
                }
                private static void _LanguageName_Validate(global::LightSwitchApplication.vilani_language e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.LanguageName_Validate(r);
                }
                private static string _LanguageName_GetImplementationValue(global::LightSwitchApplication.vilani_language.DetailsClass d)
                {
                    return d.ImplementationEntity.LanguageName;
                }
                private static void _LanguageName_SetImplementationValue(global::LightSwitchApplication.vilani_language.DetailsClass d, string v)
                {
                    d.ImplementationEntity.LanguageName = v;
                }
                private static void _LanguageName_OnValueChanged(global::LightSwitchApplication.vilani_language e)
                {
                    e.LanguageName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, string>.Entry
                    Description1 = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, string>.Entry(
                        "Description1",
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._Description1_Stub,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._Description1_ComputeIsReadOnly,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._Description1_Validate,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._Description1_GetImplementationValue,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._Description1_SetImplementationValue,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._Description1_OnValueChanged);
                private static void _Description1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.vilani_language.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, string>.Data> c, global::LightSwitchApplication.vilani_language.DetailsClass d, object sf)
                {
                    c(d, ref d._Description1, sf);
                }
                private static bool _Description1_ComputeIsReadOnly(global::LightSwitchApplication.vilani_language e)
                {
                    bool result = false;
                    e.Description1_IsReadOnly(ref result);
                    return result;
                }
                private static void _Description1_Validate(global::LightSwitchApplication.vilani_language e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Description1_Validate(r);
                }
                private static string _Description1_GetImplementationValue(global::LightSwitchApplication.vilani_language.DetailsClass d)
                {
                    return d.ImplementationEntity.Description1;
                }
                private static void _Description1_SetImplementationValue(global::LightSwitchApplication.vilani_language.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Description1 = v;
                }
                private static void _Description1_OnValueChanged(global::LightSwitchApplication.vilani_language e)
                {
                    e.Description1_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.common_developerlist>.Entry
                    common_developerlists = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.common_developerlist>.Entry(
                        "common_developerlists",
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._common_developerlists_Stub,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._common_developerlists_GetReferencedEntities,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._common_developerlists_GetEntityCollection);
                private static void _common_developerlists_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.vilani_language.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.common_developerlist>.Data> c, global::LightSwitchApplication.vilani_language.DetailsClass d, object sf)
                {
                    c(d, ref d._common_developerlists, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.common_developerlist> _common_developerlists_GetReferencedEntities(global::LightSwitchApplication.vilani_language.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.common_developerlist, global::LightSwitchApplication.common_developerlist.DetailsClass>(global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.common_developerlists, ref d._common_developerlists);
                }
                private static global::System.Collections.IEnumerable _common_developerlists_GetEntityCollection(global::LightSwitchApplication.vilani_language.DetailsClass d)
                {
                    return d.ImplementationEntity.common_developerlists;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.common_officeaddress>.Entry
                    common_officeaddresses = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.common_officeaddress>.Entry(
                        "common_officeaddresses",
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._common_officeaddresses_Stub,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._common_officeaddresses_GetReferencedEntities,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._common_officeaddresses_GetEntityCollection);
                private static void _common_officeaddresses_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.vilani_language.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.common_officeaddress>.Data> c, global::LightSwitchApplication.vilani_language.DetailsClass d, object sf)
                {
                    c(d, ref d._common_officeaddresses, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.common_officeaddress> _common_officeaddresses_GetReferencedEntities(global::LightSwitchApplication.vilani_language.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.common_officeaddress, global::LightSwitchApplication.common_officeaddress.DetailsClass>(global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.common_officeaddresses, ref d._common_officeaddresses);
                }
                private static global::System.Collections.IEnumerable _common_officeaddresses_GetEntityCollection(global::LightSwitchApplication.vilani_language.DetailsClass d)
                {
                    return d.ImplementationEntity.common_officeaddresses;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.common_officeaddress_translate>.Entry
                    common_officeaddress_translates = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.common_officeaddress_translate>.Entry(
                        "common_officeaddress_translates",
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._common_officeaddress_translates_Stub,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._common_officeaddress_translates_GetReferencedEntities,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._common_officeaddress_translates_GetEntityCollection);
                private static void _common_officeaddress_translates_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.vilani_language.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.common_officeaddress_translate>.Data> c, global::LightSwitchApplication.vilani_language.DetailsClass d, object sf)
                {
                    c(d, ref d._common_officeaddress_translates, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.common_officeaddress_translate> _common_officeaddress_translates_GetReferencedEntities(global::LightSwitchApplication.vilani_language.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.common_officeaddress_translate, global::LightSwitchApplication.common_officeaddress_translate.DetailsClass>(global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.common_officeaddress_translates, ref d._common_officeaddress_translates);
                }
                private static global::System.Collections.IEnumerable _common_officeaddress_translates_GetEntityCollection(global::LightSwitchApplication.vilani_language.DetailsClass d)
                {
                    return d.ImplementationEntity.common_officeaddress_translates;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.plot_plottingaddress>.Entry
                    plot_plottingaddresses = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.plot_plottingaddress>.Entry(
                        "plot_plottingaddresses",
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._plot_plottingaddresses_Stub,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._plot_plottingaddresses_GetReferencedEntities,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._plot_plottingaddresses_GetEntityCollection);
                private static void _plot_plottingaddresses_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.vilani_language.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.plot_plottingaddress>.Data> c, global::LightSwitchApplication.vilani_language.DetailsClass d, object sf)
                {
                    c(d, ref d._plot_plottingaddresses, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.plot_plottingaddress> _plot_plottingaddresses_GetReferencedEntities(global::LightSwitchApplication.vilani_language.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.plot_plottingaddress, global::LightSwitchApplication.plot_plottingaddress.DetailsClass>(global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.plot_plottingaddresses, ref d._plot_plottingaddresses);
                }
                private static global::System.Collections.IEnumerable _plot_plottingaddresses_GetEntityCollection(global::LightSwitchApplication.vilani_language.DetailsClass d)
                {
                    return d.ImplementationEntity.plot_plottingaddresses;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.plot_plottingaddress_translate>.Entry
                    plot_plottingaddress_translates = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.plot_plottingaddress_translate>.Entry(
                        "plot_plottingaddress_translates",
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._plot_plottingaddress_translates_Stub,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._plot_plottingaddress_translates_GetReferencedEntities,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._plot_plottingaddress_translates_GetEntityCollection);
                private static void _plot_plottingaddress_translates_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.vilani_language.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.plot_plottingaddress_translate>.Data> c, global::LightSwitchApplication.vilani_language.DetailsClass d, object sf)
                {
                    c(d, ref d._plot_plottingaddress_translates, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.plot_plottingaddress_translate> _plot_plottingaddress_translates_GetReferencedEntities(global::LightSwitchApplication.vilani_language.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.plot_plottingaddress_translate, global::LightSwitchApplication.plot_plottingaddress_translate.DetailsClass>(global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.plot_plottingaddress_translates, ref d._plot_plottingaddress_translates);
                }
                private static global::System.Collections.IEnumerable _plot_plottingaddress_translates_GetEntityCollection(global::LightSwitchApplication.vilani_language.DetailsClass d)
                {
                    return d.ImplementationEntity.plot_plottingaddress_translates;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.plot_plottingscheme_translate>.Entry
                    plot_plottingscheme_translates = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.plot_plottingscheme_translate>.Entry(
                        "plot_plottingscheme_translates",
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._plot_plottingscheme_translates_Stub,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._plot_plottingscheme_translates_GetReferencedEntities,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._plot_plottingscheme_translates_GetEntityCollection);
                private static void _plot_plottingscheme_translates_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.vilani_language.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.plot_plottingscheme_translate>.Data> c, global::LightSwitchApplication.vilani_language.DetailsClass d, object sf)
                {
                    c(d, ref d._plot_plottingscheme_translates, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.plot_plottingscheme_translate> _plot_plottingscheme_translates_GetReferencedEntities(global::LightSwitchApplication.vilani_language.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.plot_plottingscheme_translate, global::LightSwitchApplication.plot_plottingscheme_translate.DetailsClass>(global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.plot_plottingscheme_translates, ref d._plot_plottingscheme_translates);
                }
                private static global::System.Collections.IEnumerable _plot_plottingscheme_translates_GetEntityCollection(global::LightSwitchApplication.vilani_language.DetailsClass d)
                {
                    return d.ImplementationEntity.plot_plottingscheme_translates;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.realestate_property>.Entry
                    realestate_properties = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.realestate_property>.Entry(
                        "realestate_properties",
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._realestate_properties_Stub,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._realestate_properties_GetReferencedEntities,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._realestate_properties_GetEntityCollection);
                private static void _realestate_properties_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.vilani_language.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.realestate_property>.Data> c, global::LightSwitchApplication.vilani_language.DetailsClass d, object sf)
                {
                    c(d, ref d._realestate_properties, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.realestate_property> _realestate_properties_GetReferencedEntities(global::LightSwitchApplication.vilani_language.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.realestate_property, global::LightSwitchApplication.realestate_property.DetailsClass>(global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.realestate_properties, ref d._realestate_properties);
                }
                private static global::System.Collections.IEnumerable _realestate_properties_GetEntityCollection(global::LightSwitchApplication.vilani_language.DetailsClass d)
                {
                    return d.ImplementationEntity.realestate_properties;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.realestate_property_translate>.Entry
                    realestate_property_translates = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.realestate_property_translate>.Entry(
                        "realestate_property_translates",
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._realestate_property_translates_Stub,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._realestate_property_translates_GetReferencedEntities,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._realestate_property_translates_GetEntityCollection);
                private static void _realestate_property_translates_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.vilani_language.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.realestate_property_translate>.Data> c, global::LightSwitchApplication.vilani_language.DetailsClass d, object sf)
                {
                    c(d, ref d._realestate_property_translates, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.realestate_property_translate> _realestate_property_translates_GetReferencedEntities(global::LightSwitchApplication.vilani_language.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.realestate_property_translate, global::LightSwitchApplication.realestate_property_translate.DetailsClass>(global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.realestate_property_translates, ref d._realestate_property_translates);
                }
                private static global::System.Collections.IEnumerable _realestate_property_translates_GetEntityCollection(global::LightSwitchApplication.vilani_language.DetailsClass d)
                {
                    return d.ImplementationEntity.realestate_property_translates;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.common_developerlist_translate>.Entry
                    common_developerlist_translates = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.common_developerlist_translate>.Entry(
                        "common_developerlist_translates",
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._common_developerlist_translates_Stub,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._common_developerlist_translates_GetReferencedEntities,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._common_developerlist_translates_GetEntityCollection);
                private static void _common_developerlist_translates_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.vilani_language.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.common_developerlist_translate>.Data> c, global::LightSwitchApplication.vilani_language.DetailsClass d, object sf)
                {
                    c(d, ref d._common_developerlist_translates, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.common_developerlist_translate> _common_developerlist_translates_GetReferencedEntities(global::LightSwitchApplication.vilani_language.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.common_developerlist_translate, global::LightSwitchApplication.common_developerlist_translate.DetailsClass>(global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.common_developerlist_translates, ref d._common_developerlist_translates);
                }
                private static global::System.Collections.IEnumerable _common_developerlist_translates_GetEntityCollection(global::LightSwitchApplication.vilani_language.DetailsClass d)
                {
                    return d.ImplementationEntity.common_developerlist_translates;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.common_propertycontactperson_translate>.Entry
                    common_propertycontactperson_translates = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.common_propertycontactperson_translate>.Entry(
                        "common_propertycontactperson_translates",
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._common_propertycontactperson_translates_Stub,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._common_propertycontactperson_translates_GetReferencedEntities,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._common_propertycontactperson_translates_GetEntityCollection);
                private static void _common_propertycontactperson_translates_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.vilani_language.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.common_propertycontactperson_translate>.Data> c, global::LightSwitchApplication.vilani_language.DetailsClass d, object sf)
                {
                    c(d, ref d._common_propertycontactperson_translates, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.common_propertycontactperson_translate> _common_propertycontactperson_translates_GetReferencedEntities(global::LightSwitchApplication.vilani_language.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.common_propertycontactperson_translate, global::LightSwitchApplication.common_propertycontactperson_translate.DetailsClass>(global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.common_propertycontactperson_translates, ref d._common_propertycontactperson_translates);
                }
                private static global::System.Collections.IEnumerable _common_propertycontactperson_translates_GetEntityCollection(global::LightSwitchApplication.vilani_language.DetailsClass d)
                {
                    return d.ImplementationEntity.common_propertycontactperson_translates;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.plot_plotowner_translate>.Entry
                    plot_plotowner_translates = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.plot_plotowner_translate>.Entry(
                        "plot_plotowner_translates",
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._plot_plotowner_translates_Stub,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._plot_plotowner_translates_GetReferencedEntities,
                        global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties._plot_plotowner_translates_GetEntityCollection);
                private static void _plot_plotowner_translates_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.vilani_language.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.plot_plotowner_translate>.Data> c, global::LightSwitchApplication.vilani_language.DetailsClass d, object sf)
                {
                    c(d, ref d._plot_plotowner_translates, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.plot_plotowner_translate> _plot_plotowner_translates_GetReferencedEntities(global::LightSwitchApplication.vilani_language.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.plot_plotowner_translate, global::LightSwitchApplication.plot_plotowner_translate.DetailsClass>(global::LightSwitchApplication.vilani_language.DetailsClass.PropertySetProperties.plot_plotowner_translates, ref d._plot_plotowner_translates);
                }
                private static global::System.Collections.IEnumerable _plot_plotowner_translates_GetEntityCollection(global::LightSwitchApplication.vilani_language.DetailsClass d)
                {
                    return d.ImplementationEntity.plot_plotowner_translates;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, int>.Data _LanguageID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, string>.Data _LanguageName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, string>.Data _Description1;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.common_developerlist>.Data _common_developerlists;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.common_officeaddress>.Data _common_officeaddresses;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.common_officeaddress_translate>.Data _common_officeaddress_translates;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.plot_plottingaddress>.Data _plot_plottingaddresses;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.plot_plottingaddress_translate>.Data _plot_plottingaddress_translates;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.plot_plottingscheme_translate>.Data _plot_plottingscheme_translates;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.realestate_property>.Data _realestate_properties;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.realestate_property_translate>.Data _realestate_property_translates;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.common_developerlist_translate>.Data _common_developerlist_translates;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.common_propertycontactperson_translate>.Data _common_propertycontactperson_translates;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.vilani_language, global::LightSwitchApplication.vilani_language.DetailsClass, global::LightSwitchApplication.plot_plotowner_translate>.Data _plot_plotowner_translates;
            
        }
    
        #endregion
    }
    
    #endregion
}
